version: "3.9"

services:
  backend:
    build: ./backend
    container_name: final_buddy_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - qdrant
    volumes:
      - ./backend:/app
      - ./final_images:/app/final_images
      - ./pehchaan:/app/pehchaan
      - ./visual_embed:/app/visual_embed
    restart: always

  postgres:
    image: postgres:15
    container_name: final_buddy_postgres
    environment:
      POSTGRES_DB: faces_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant
    container_name: final_buddy_qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage